<a href="https://colab.research.google.com/github/sacalgo/Assignments/blob/MFA/EigenValuesVectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
#Data
mat = [
  [9.07, -9.21, -0.73],
  [-9.21, 129.93, 91.54],
  [-0.73, 91.54, 684.7]
]

In [24]:
import numpy as np
mat=np.array(mat)
eigen_values, eigen_vectors = np.linalg.eig(mat)
print("EigenValues:", np.round(eigen_values, 3))
print("eigenVectors:")
# print(eigen_vectors)
print(np.round(eigen_vectors, 3))


EigenValues: [  8.309 115.97  699.421]
eigenVectors:
[[-0.996 -0.084 -0.003]
 [-0.083  0.984  0.159]
 [ 0.01  -0.158  0.987]]
