<a href="https://colab.research.google.com/github/sacalgo/Assignments/blob/MFA/Inverse_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#inverse matrix

import numpy as np
mat = [
  [9.07, -9.21, -0.73],
  [-9.21, 129.93, 91.54],
  [-0.73, 91.54, 684.7]
]
mat= np.array(mat)
inverse=np.linalg.inv(mat)
# print(inverse)
print(np.round(inverse, 5))

[[ 0.11956  0.00926 -0.00111]
 [ 0.00926  0.00921 -0.00122]
 [-0.00111 -0.00122  0.00162]]
